apiVersion: apps/v1
kind: Deployment
metadata:
  name: chienthan2-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chienthan2
  template:
    metadata:
      labels:
        app: chienthan2
    spec:
      containers:
      - name: chienthan2
        image: nguyenanhtu3101/chienthan2:19
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chienthan2-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
  selector:
    app: chienthan2