apiVersion: apps/v1
kind: Deployment
metadata:
  name: chienthan1demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chienthan2
  template:
    metadata:
      labels:
        app: chienthan2
    spec:
      containers:
      - name: chienthan2
        image: nguyenanhtu3101/chienthan2:19
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: chienthan2demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7000
    nodePort: 32000
  selector:
    app: chienthan2