apiVersion: apps/v1
kind: Deployment
metadata:
  name: chienthandemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chienthan2
  template:
    metadata:
      labels:
        app: chienthan2
    spec:
      containers:
      - name: chienthan2
        image: nguyenanhtu3101/anhtucicd:latest
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: chienthandemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 7000
    nodePort: 31111
  selector:
    app: chienthan2
